[tool.ruff]
exclude = [
  ".direnv",
  ".git",
  ".pyenv",
  ".vscode",
  "venv",
  ".venv",
  ".pytest_cache",
  ".mypy_cache",
  "__pycache__",
]
line-length = 160
target-version = "py311"

[tool.ruff.lint]
select = [
  "E",  # pycodestyle
  "F",  # pyflakes
  "W",  # pycodestyle
  "I",  # isort
  "B",  # flake8-bugbear
  "UP", # pyupgrade
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
quote-style = "double"
line-ending = "auto"

[tool.mypy]
plugins = [
  "sqlalchemy.ext.mypy.plugin",
  "pydantic.mypy",
]

ignore_missing_imports = true
exclude = [
  "alembic",
  "venv",
  ".venv",
  ".direnv",
]
