name: Build_and_Test

on:
  push:
    branches: [main]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.9"

  #     - name: Install dependencies
  #       run: pip install -r requirements.txt

  #     - name: Run tests
  #       run: pytest

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build Docker image
  #       run: docker build -t haldekhiel/devopsproject:latest .

  #     - name: Push Docker image
  #       run: docker push haldekhiel/devopsproject:latest
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker Username
        run: echo ${{ secrets.DOCKER_USERNAME }}

      - name: Check Docker Password
        run: echo ${{ secrets.DOCKERHUB_TOKEN }}